<a href="https://colab.research.google.com/github/Parthiv0121/AI-Lawyer-Assistant/blob/main/LSTM_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM



In [ ]:
mytext = """ orbes has been scanning the globe for billionaires since 1987. We found 140 of them that first year. It took two decades for their numbers to swell beyond 1,000. Then there were 2,000 in 2017. Now, eight years later, another milestone: 3,028 entrepreneurs, investors and heirs make up this year’s ranking, 247 more than a year ago. Not only are there more of them, but they’re richer than ever, worth $16.1 trillion in total—up nearly $2 trillion over 2024. The U.S. has a record 902 billionaires, followed by China (516, including Hong Kong) and India (205). We used stock prices and exchange rates from March 7, 2025. For daily updated net worths of all 3,028 billionaires, check out our real-time billionaires ranking."""

In [ ]:
mytext

' orbes has been scanning the globe for billionaires since 1987. We found 140 of them that first year. It took two decades for their numbers to swell beyond 1,000. Then there were 2,000 in 2017. Now, eight years later, another milestone: 3,028 entrepreneurs, investors and heirs make up this year’s ranking, 247 more than a year ago. Not only are there more of them, but they’re richer than ever, worth $16.1 trillion in total—up nearly $2 trillion over 2024. The U.S. has a record 902 billionaires, followed by China (516, including Hong Kong) and India (205). We used stock prices and exchange rates from March 7, 2025. For daily updated net worths of all 3,028 billionaires, check out our real-time billionaires ranking.'

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])

total_words = len(mytokenizer.word_index) + 1


In [ ]:
mytokenizer.word_index

{'billionaires': 1,
 'for': 2,
 'of': 3,
 'and': 4,
 'has': 5,
 'the': 6,
 'we': 7,
 'them': 8,
 'year': 9,
 '1': 10,
 '000': 11,
 'there': 12,
 '2': 13,
 'in': 14,
 '3': 15,
 '028': 16,
 'ranking': 17,
 'more': 18,
 'than': 19,
 'a': 20,
 'trillion': 21,
 'orbes': 22,
 'been': 23,
 'scanning': 24,
 'globe': 25,
 'since': 26,
 '1987': 27,
 'found': 28,
 '140': 29,
 'that': 30,
 'first': 31,
 'it': 32,
 'took': 33,
 'two': 34,
 'decades': 35,
 'their': 36,
 'numbers': 37,
 'to': 38,
 'swell': 39,
 'beyond': 40,
 'then': 41,
 'were': 42,
 '2017': 43,
 'now': 44,
 'eight': 45,
 'years': 46,
 'later': 47,
 'another': 48,
 'milestone': 49,
 'entrepreneurs': 50,
 'investors': 51,
 'heirs': 52,
 'make': 53,
 'up': 54,
 'this': 55,
 'year’s': 56,
 '247': 57,
 'ago': 58,
 'not': 59,
 'only': 60,
 'are': 61,
 'but': 62,
 'they’re': 63,
 'richer': 64,
 'ever': 65,
 'worth': 66,
 '16': 67,
 'total—up': 68,
 'nearly': 69,
 'over': 70,
 '2024': 71,
 'u': 72,
 's': 73,
 'record': 74,
 '902': 75,
 'fo

In [ ]:
my_input_sequence = []
for  line in mytext.split('\n'):
  token_list = mytokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    my_n_gram_sequence = token_list[:i+1]
    print(my_n_gram_sequence)
    my_input_sequence.append(my_n_gram_sequence)

[22, 5]
[22, 5, 23]
[22, 5, 23, 24]
[22, 5, 23, 24, 6]
[22, 5, 23, 24, 6, 25]
[22, 5, 23, 24, 6, 25, 2]
[22, 5, 23, 24, 6, 25, 2, 1]
[22, 5, 23, 24, 6, 25, 2, 1, 26]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30, 31]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30, 31, 9]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30, 31, 9, 32]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30, 31, 9, 32, 33]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30, 31, 9, 32, 33, 34]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30, 31, 9, 32, 33, 34, 35]
[22, 5, 23, 24, 6, 25, 2, 1, 26, 27, 7, 28, 29, 3, 8, 30, 31, 9, 32, 33, 34

In [ ]:
max_sequence_len = max([len(seq) for seq in my_input_sequence])

In [ ]:
max_sequence_len

129

In [ ]:
input_sequences =np.array(pad_sequences(my_input_sequence, maxlen=max_sequence_len , padding='pre'))

In [ ]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, 22,  5, 23], dtype=int32)

In [ ]:
X= input_sequences[:,:-1]
Y= input_sequences[:,-1]

In [ ]:
X[2]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 22,  5, 23], dtype=int32)

In [ ]:
Y[2]

np.int32(24)

In [ ]:
y = np.array(tf.keras.utils.to_categorical(Y, num_classes=total_words))

In [ ]:
y[2]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [ ]:
model = Sequential()
model.add(Embedding(total_words, 120 , input_length= max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 128, 120)       │        12,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 150)            │       162,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 104)            │        15,704 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 190,784 (745.25 KB)

 Trainable params: 190,784 (745.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.build(input_shape=(None, max_sequence_len-1))

In [ ]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X,y , epochs=100 , verbose=2)

Epoch 1/100
4/4 - 4s - 895ms/step - accuracy: 0.0156 - loss: 4.6448
Epoch 2/100
4/4 - 2s - 403ms/step - accuracy: 0.1016 - loss: 4.6288
Epoch 3/100
4/4 - 2s - 444ms/step - accuracy: 0.1484 - loss: 4.6101
Epoch 4/100
4/4 - 1s - 209ms/step - accuracy: 0.0625 - loss: 4.5843
Epoch 5/100
4/4 - 1s - 213ms/step - accuracy: 0.0781 - loss: 4.5289
Epoch 6/100
4/4 - 1s - 208ms/step - accuracy: 0.1172 - loss: 4.5053
Epoch 7/100
4/4 - 1s - 200ms/step - accuracy: 0.1484 - loss: 4.4317
Epoch 8/100
4/4 - 1s - 213ms/step - accuracy: 0.0938 - loss: 4.3717
Epoch 9/100
4/4 - 1s - 212ms/step - accuracy: 0.1250 - loss: 4.2773
Epoch 10/100
4/4 - 1s - 214ms/step - accuracy: 0.1094 - loss: 4.1866
Epoch 11/100
4/4 - 1s - 215ms/step - accuracy: 0.0938 - loss: 4.0790
Epoch 12/100
4/4 - 1s - 207ms/step - accuracy: 0.1016 - loss: 3.9620
Epoch 13/100
4/4 - 1s - 213ms/step - accuracy: 0.0938 - loss: 3.8346
Epoch 14/100
4/4 - 2s - 510ms/step - accuracy: 0.0938 - loss: 3.7031
Epoch 15/100
4/4 - 1s - 328ms/step - accura

In [ ]:
input_text= "orbes"
predict_next_word=10

for _ in range(predict_next_word):
  token_list = mytokenizer.texts_to_sequences([input_text])[0]
  token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
  predicted=np.argmax(model.predict(token_list), axis=-1)
  output_word = ""
  for word, index in mytokenizer.word_index.items():
    if index == predicted:
      output_word = word
      break
  input_text += " " + output_word
print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
orbes has been scanning the globe for billionaires since 1987 we
